<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c5442d36-184f-47d6-83b3-9d3d8c0e4652</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Types\External\Alegra\" />
    <Folder Include="Types\Models\" />
    <Folder Include="Types\Enums\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="RecursosPetra\RsSQL\RsUsuario.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RsUsuario.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="RecursosPetra\RsSQL\RsUsuario.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>RsUsuario.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
